services:
  data:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.18-alpine
    platform: linux/amd64
    depends_on:
      - data
    command: ["-configFiles=/flyway/conf/flyway.conf"]
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/migrations/sql:/flyway/sql
      - ./data/migrations/flyway.conf:/flyway/conf/flyway.conf:ro

volumes:
  postgres_data:
